export const UPDATE_SUPER_MEMO_CURRENT_STEP = "UPDATE_SUPER_MEMO_CURRENT_STEP";
export const INIT_SUPER_MEMO_PARAMS = "INIT_SUPER_MEMO_PARAMS";
export const RESET_SUPER_MEMO_STATE = "RESET_SUPER_MEMO_STATE";
